### ISSUE TITLE
自定义代理器

### ISSUE THREAD

**Issue by CaesarChan** [toplan/phpsms#111]
自定义代理器类使用 Toplan/PhpSms 命名空间
对于Laravel项目 ,在重新执行 php artisan optimize ,生成的 autoload_classmap.php
中也不会出现自定义的类的相关映射.
`$className = "Toplan\\PhpSms\\{$name}Agent";`
` class_exists($className);`

**Comment by toplan** [comment]
laravel 的 autoload 采用的 prs-4 规范，自己在工程中加的类需要符合相应的规范，不然就到 composer.json 里面 autoload 里面的 classmap 里手动添加。

**Comment by toplan** [comment]
加入我在app目录下jia加这样一个代理器 HiAgent
![image](https://cloud.githubusercontent.com/assets/7815594/26244990/afe55396-3cc4-11e7-8daa-9e6bea04a0e4.png)

那么需要到 composer.json 中 autoload 里的 classmap 加入相应的类
![image](https://cloud.githubusercontent.com/assets/7815594/26245026/d1435c86-3cc4-11e7-925f-22311cad96aa.png)

**Comment by toplan** [comment]
或者符合 psr-4 的规范，像这样加入一个 TestAgent
![image](https://cloud.githubusercontent.com/assets/7815594/26245062/0344ec54-3cc5-11e7-84be-7c240db86f27.png)
那么就不用手动去 composer.json 修改了

**Comment by CaesarChan** [comment]
谢谢楼主.我是手动改的加载文件(还是符合项目规范好点).这个问题算是对文档的补充.
