### ISSUE TITLE
"toplan/phpsms": "~1.8.0-beta",  composer update 报错

### ISSUE THREAD

**Issue by kideny** [toplan/phpsms#113]
Problem 1
    - Installation request for toplan/phpsms ~1.8.0-beta -> satisfiable by toplan/phpsms[1.8.0-beta.1].
    - toplan/phpsms 1.8.0-beta.1 requires toplan/task-balancer ~0.5.0-beta -> satisfiable by toplan/task-balancer[0.5.0-beta.1] but these conflict with your requirements or minimum-stability.

**Comment by kideny** [comment]
"toplan/phpsms": "~1.8.0-beta",

composer.json添加了这个，然后报错。

**Comment by onwulc** [comment]
dependencies 是 toplan/task-balancer ~0.5.0-beta，实际上toplan/task-balancer 的是 toplan/task-balancer ~0.5.0-beta.1

要么官方fix，要么自己fork

**Comment by toplan** [comment]
已发布1.8

**Comment by kideny** [comment]
@toplan  多谢！
