### ISSUE TITLE
使用云片发送短信时报错

### ISSUE THREAD

**Issue by yuyifly82** [toplan/phpsms#114]
我把phpsms升级到1.8.0后云片发送短信时报错，我查看了下错误，应该是在Agent.php中curl()处循环读取$opts时报错，
 foreach ($opts as $key => $value) {
            curl_setopt($ch, $key, $value);
        }
我将其改成  
curl_setopt($ch, CURLOPT_SSL_POST,$opts[3]);
curl_setopt($ch, CURLOPT_SSL_HTTPHEADER,$opts[1]);
curl_setopt($ch, CURLOPT_SSL_POSTFIELDS,http_query_bulid($opts[0]));
curl_setopt($ch, CURLOPT_SSL_HTTPURL,$opts[4]);
以后就正常发送云片短信了。

**Comment by toplan** [comment]
确实有bug，谢谢指出
