### ISSUE TITLE
qcloud短信api错误

### ISSUE THREAD

**Issue by qinxg** [toplan/phpsms#120]
`{
    "tel": { //如需使用国际电话号码通用格式，如："+8613788888888" ，请使用sendisms接口见下注
        "nationcode": "86", //国家码
        "mobile": "13788888888" //手机号码
    }, 
    "type": 0, //0:普通短信;1:营销短信（强调：要按需填值，不然会影响到业务的正常使用）
    "msg": "你的验证码是1234", //utf8编码 
    "sig": "30db206bfd3fea7ef0db929998642c8ea54cc7042a779c5a0d9897358f6e9505", //app凭证，具体计算方式见下注
    "time": 1457336869, //unix时间戳，请求发起时间，如果和系统时间相差超过10分钟则会返回失败
    "extend": "", //通道扩展码，可选字段，默认没有开通(需要填空)。
     //在短信回复场景中，腾讯server会原样返回，开发者可依此区分是哪种类型的回复
    "ext": "" //用户的session内容，腾讯server回包中会原样返回，可选字段，不需要就填空。
}`

注意电话号码那一部分。是tel:{}  不是接收固定号码

详情：
https://www.qcloud.com/document/api/382/5808

**Comment by toplan** [comment]
感谢反馈，我会尽快处理
