### ISSUE TITLE
CCPRestSmsSDK报错

### ISSUE THREAD

**Issue by hardywen** [toplan/phpsms#20]
使用YunTongXun Agent时，该Agent调用了 CCPRestSmsSDK，但传入的$filename为 null，导致报错，
错误信息：fopen(): Filename cannot be empty
代码在：
https://github.com/toplan/phpsms/blob/master/src/phpsms/lib/CCPRestSmsSDK.php#L37

**Comment by toplan** [comment]
I got it! 谢谢反馈!

**Comment by hardywen** [comment]
希望可以尽快出一个修改这个Bug的版本，比较急用，谢谢

**Comment by toplan** [comment]
@hardywen 已发布v1.2.1
