### ISSUE TITLE
YunTongXun 短信发送成功状态判断有误

### ISSUE THREAD

**Issue by hardywen** [toplan/phpsms#23]
现在短信发送成功判断用的是 
```php
$result->statusCode === 0
 ```
但实际上，云通讯的状态码是  000000 。所以现在短信发送成功了，但组件返回结果 $result['success'] 为 false

ps: 云通讯和云之讯的接口几乎一样的，只是某些接口路径有一点点不同，如果有时间的话，可以考虑改成共用一个 lib .

**Comment by toplan** [comment]
:+1: got it! 待会我会测试并修改。另外接口这一块，以后都会尽量统一用Agent::curl()或者Agent::scokPost()方法

**Comment by toplan** [comment]
@hardywen 已发布[v1.2.2](https://github.com/toplan/phpsms/releases/tag/1.2.2)，再次感谢你的支持和反馈！ :smile_cat:
