### ISSUE TITLE
阿里云也出短信接口了，交阿里大鱼，希望能整合进来。

### ISSUE THREAD

**Issue by OranTing** [toplan/phpsms#27]
官网：
http://www.alidayu.com/?spm=a3142.7791109.1.1.6AQ1vP

阿里云的东西应该比较靠谱 稳定，希望可以整合。@toplan

**Comment by toplan** [comment]
@OranTing ok! 我会尽快安排时间处理，感谢你的建议

**Comment by spc324** [comment]
大概什么时候能加入阿里大鱼呢

**Comment by toplan** [comment]
这两个月公司开发新项目和私事比较多，这周项目会告一段落，会有精力和心思维护该项目的

**Comment by OranTing** [comment]
嗯，很期待。

**Comment by geekxm** [comment]
同期待能添加阿里大鱼。顶！d=====(￣▽￣*)b

**Comment by toplan** [comment]
各位小伙伴，我刚刚看了下阿里大鱼的文档，有个疑惑，文档里说“由于应用要先拥有API的访问权限，才能调用此API，所以SDK的下载是与应用相关联的，不同的应用下载到的SDK是各不一样的。”，按照这么说，无法使用阿里大鱼提高的sdk作为通用的sdk对吧？各位有什么意见和看法吗？

**Comment by branchzero** [comment]
@toplan 可以参考 http://open.taobao.com/doc2/apiDetail?apiId=25450 和 http://open.taobao.com/doc2/apiDetail?apiId=25445，下面有一个 CURL 的示例。
刚好这两天给一个客户开发东西，要用到大鱼的接口，等我弄完我发一个 PR 贡献下吧。

**Comment by toplan** [comment]
@branchzero 已合并

**Comment by sinkcup** [comment]
阿里云又出了一个短信服务……和阿里大于不一样
https://www.aliyun.com/product/sms
