### ISSUE TITLE
为什么返回成功，却没收到短信！

### ISSUE THREAD

**Issue by yingzhzh** [toplan/phpsms#34]
![qq 20160316142422](https://cloud.githubusercontent.com/assets/17507858/13803824/cbbb36b0-eb82-11e5-9070-5a3ab44587ec.png)
云片啊，配置也不会错，就填了apikey

**Comment by yingzhzh** [comment]
我配置写在config/phpsms里有不行，写在代码里就可以

**Comment by toplan** [comment]
你好，根据返回结果来看，系统并没有使用云片代理器`YunPian`发送短信，而是使用的测试用代理器`Log`。你需要在config/phpsms的`enable`键修改`Log`为`YunPian`。

**Comment by yingzhzh** [comment]
![image](https://cloud.githubusercontent.com/assets/17507858/13804497/653c15fc-eb88-11e5-8196-989fa75a06c2.png)还是没接收到，刚才phpsms收到了一条，然后我换回laravelsms失败了

**Comment by toplan** [comment]
laravel-sms默认使用了队列系统的，你可以通过PhpSms::queue(false)关闭队列系统。如果不关闭，需要监听队列任务`php artisan queue:listen`

**Comment by yingzhzh** [comment]
默认应该关闭啊

**Comment by toplan** [comment]
是的，感谢你的反馈 :smile_cat:

**Comment by yingzhzh** [comment]
要么在前面部分说明下，要不然测试怎么都不行

**Comment by toplan** [comment]
Laravel sms已发布2.2.7以修复该问题，再次感谢你的反馈
