### ISSUE TITLE
beforeDriverRun建议

### ISSUE THREAD

**Issue by xjdata** [toplan/phpsms#38]
提供了beforeDriverRun 但是beforeDriverRun中无法标记当前agent 失效.

比如, 目前发送短信会有某个时间内的次数限制,当之前已经使用某agent进行发送了.之后又多次请求.

按理说,发送不成功应该不会计费, 但是目前的短信网关一般都是不发送,但是进行计费的.

如果在beforeDriverRun 时根据当前agent的判断, 进行当前agent跳过或直接标记agent错误,那就会好很多了.

**Comment by toplan** [comment]
@xjdata 已经发布`v1.2.3`, 在`beforeDriverRun`中返回`false`则会标记当前agent失败，且系统自动尝试下一个备用agent。当然如果不反回(其实就是返回null)或者返回`true`，则按正常流程走。

**Comment by xjdata** [comment]
多谢~~~  

话说我搞了 大鱼的agent, 

但是git不会. 加上水平太菜,就不献丑了. 

不过对你来说开发真的是分分钟的事情, 

就是引用的大鱼的sdk不带namespace,稍微麻烦点.
