### ISSUE TITLE
能否提供一个队列实现的例子呢?

### ISSUE THREAD

**Issue by xjdata** [toplan/phpsms#77]
允许推入队列，并自定义队列实现逻辑(与队列系统松散耦合)。

比如 将队列存储到数据库,然后定时任务发送什么的. 要求比较过分, 不知道能否考虑.

**Comment by toplan** [comment]
这有个例子：https://github.com/toplan/laravel-sms/blob/master/src/Toplan/LaravelSms/SmsManagerServiceProvider.php#L60
