### ISSUE TITLE
  [Toplan\PhpSms\PhpSmsException]                                                                     Modify the dispatch scheme failed for [Log] agent, because the task system has already started.  

### ISSUE THREAD

**Issue by QylinFly** [toplan/phpsms#96]
[Toplan\PhpSms\PhpSmsException]                                                                  
  Modify the dispatch scheme failed for [Log] agent, because the task system has already started.

**Comment by toplan** [comment]
@QylinFly 你好，这个是`laravel-sms`的一个bug，可以暂时这样处理：
SmsManagerServiceProvider里面`register`方法里面的`$this->initPhpSms()`移动到`boot`方法里

然后等待我发布新版本更新这个bug...

**Comment by toplan** [comment]
请移步到这里 https://github.com/toplan/laravel-sms/issues/136
